In [1]:
print("Hello")

Hello


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print(tf.config.list_physical_devices('GPU'))
print(tf.config.list_physical_devices("CPU"))

TensorFlow version: 2.10.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)
x_train, x_test = x_train / 255.0, x_test / 255.0

(60000, 28, 28) (60000,)


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.00714928,  0.1075718 ,  0.54948246, -0.43528563,  0.2851324 ,
         0.40104777, -0.5559323 ,  0.33919227,  0.35130203, -0.39291096]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0227 - accuracy: 0.9923
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0221 - accuracy: 0.9925
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0206 - accuracy: 0.9925
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0207 - accuracy: 0.9929
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0207 - accuracy: 0.9930


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0730 - accuracy: 0.9780 - 318ms/epoch - 1ms/step


[0.07304070889949799, 0.9779999852180481]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.7203935e-08, 8.0705611e-09, 3.8551203e-05, 1.3615393e-04,
        7.3922243e-11, 3.8900144e-08, 1.0214479e-14, 9.9982017e-01,
        5.4012526e-07, 4.5796814e-06],
       [2.5241627e-07, 1.2191373e-05, 9.9997818e-01, 7.1907289e-06,
        2.3629574e-15, 2.2885239e-07, 3.3539149e-07, 3.1247255e-11,
        1.6680796e-06, 2.2575482e-10],
       [1.6037764e-07, 9.9842024e-01, 2.1109682e-04, 1.2607612e-05,
        3.3112450e-05, 2.3141263e-06, 7.4520749e-06, 1.1985420e-03,
        1.0945419e-04, 5.0243543e-06],
       [9.9959785e-01, 2.2214635e-08, 1.9252055e-05, 2.7393310e-07,
        9.7310613e-06, 6.4596238e-06, 1.8057822e-04, 1.4085676e-04,
        2.0948639e-06, 4.3007665e-05],
       [8.2847628e-06, 1.9301478e-08, 3.2440350e-06, 8.9545487e-08,
        9.9786633e-01, 2.6224159e-08, 1.0981647e-06, 7.2248557e-05,
        3.8623598e-06, 2.0448123e-03]], dtype=float32)>